development:
  adapter: postgresql
  #prepared_statements: false
  encoding: unicode
  database: declarations_development
  pool: 5

staging:
  adapter: postgresql
  #prepared_statements: false
  encoding: unicode
  database: declarations_staging
  pool: 5

production:
  adapter: postgresql
  #prepared_statements: false
  encoding: unicode
  database: declarations_production
  pool: 5
