development:
  facebook_key:
  facebook_secret:
  twitter_key:
  twitter_secret:
  vkontakte_key:
  vkontakte_secret:
  google_key:
  google_secret:
  mailru_key:
  mailru_secret:

production:
  facebook_key:
  facebook_secret:
  twitter_key:
  twitter_secret:
  vkontakte_key:
  vkontakte_secret:
  google_key:
  google_secret:
  mailru_key:
  mailru_secret:

staging:
  facebook_key:
  facebook_secret:
  twitter_key:
  twitter_secret:
  vkontakte_key:
  vkontakte_secret:
  google_key:
  google_secret:
  mailru_key:
  mailru_secret:

test:
  facebook_key:
  facebook_secret:
  twitter_key:
  twitter_secret:
  vkontakte_key:
  vkontakte_secret:
  google_key:
  google_secret:
  mailru_key:
  mailru_secret:
